import type { SchemaOutput } from './schemas';

export interface RuntimeOutput {
  execution_valid: boolean;
  files_generated: number;
  react_components: { name: string; code: string }[];
  express_routes: string;
  db_migration: string;
  cross_references_verified: number;
  issues: string[];
}

export function generateRuntime(schema: SchemaOutput): RuntimeOutput {
  const reactComponents = generateReactComponents(schema);
  const expressRoutes = generateExpressRoutes(schema);
  const dbMigration = generateDbMigration(schema);
  const { verified, issues } = verifyCrossReferences(schema, expressRoutes, dbMigration);

  return {
    execution_valid: issues.length === 0,
    files_generated: reactComponents.length + 2,
    react_components: reactComponents,
    express_routes: expressRoutes,
    db_migration: dbMigration,
    cross_references_verified: verified,
    issues,
  };
}

function generateReactComponents(schema: SchemaOutput): { name: string; code: string }[] {
  return schema.ui_schema.pages.map(page => {
    const componentName = page.name.replace(/\s+/g, '') + 'Page';
    const endpoints = schema.api_schema.endpoints.filter(ep =>
      page.components.some(c => c.api_endpoint === ep.id)
    );

    const fetchCalls = endpoints.map(ep => {
      const varName = ep.db_table + 'Data';
      return `
  // Fetches from: ${ep.method} ${ep.path}
  const [${varName}, set${capitalize(varName)}] = useState<any[]>([]);
  useEffect(() => {
    fetch('/api/v1${ep.path}', {
      headers: { 'Authorization': \`Bearer \${localStorage.getItem('token')}\` }
    }).then(r => r.json()).then(data => set${capitalize(varName)}(data));
  }, []);`;
    }).join('\n');

    const tableRenders = page.components.map(comp => {
      return `      {/* ${comp.type}: ${comp.id} → ${comp.api_endpoint} */}
      <div className="${comp.type.toLowerCase()}-component" data-endpoint="${comp.api_endpoint}">
        <h2>${comp.id}</h2>
      </div>`;
    }).join('\n');

    return {
      name: componentName,
      code: `// Auto-generated by AppForge Runtime Simulator
// Page: ${page.name} | Path: ${page.path} | Layout: ${page.layout}

import React, { useState, useEffect } from 'react';

export default function ${componentName}() {
${fetchCalls}

  return (
    <div className="${page.layout}-layout">
      <h1>${page.name}</h1>
${tableRenders}
    </div>
  );
}
`,
    };
  });
}

function generateExpressRoutes(schema: SchemaOutput): string {
  const routes = schema.api_schema.endpoints.map(ep => {
    const fields = ep.request_body.fields.map(f => f.name).join(', ');
    const bodyDestructure = fields ? `  const { ${fields} } = req.body;` : '';
    const roleCheck = ep.roles_allowed.length > 0
      ? `requireRole(['${ep.roles_allowed.join("', '")}'])`
      : 'authenticateJWT';

    return `
// ${ep.method} ${ep.path}
// Auth: ${ep.auth_required} | Roles: ${ep.roles_allowed.join(', ')}
// DB Table: ${ep.db_table}
router.${ep.method.toLowerCase()}('${ep.path}', authenticateJWT, ${roleCheck}, async (req, res) => {
  try {
${bodyDestructure}
    // DB: ${ep.method === 'GET' ? `SELECT * FROM ${ep.db_table}` : `INSERT/UPDATE INTO ${ep.db_table}`}
    res.${ep.method === 'POST' ? 'status(201).' : ''}json({ data: [], message: 'AppForge stub' });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});`;
  }).join('\n');

  return `// Auto-generated by AppForge Runtime Simulator
const express = require('express');
const router = express.Router();
const { authenticateJWT, requireRole } = require('../middleware/auth');

${routes}

module.exports = router;
`;
}

function generateDbMigration(schema: SchemaOutput): string {
  const tables = schema.db_schema.tables.map(table => {
    const columns = table.columns.map(col => {
      let def = `  ${col.name} `;
      switch (col.type) {
        case 'uuid': def += col.primary_key ? 'UUID PRIMARY KEY DEFAULT gen_random_uuid()' : 'UUID'; break;
        case 'varchar': def += 'VARCHAR(255)'; break;
        case 'text': def += 'TEXT'; break;
        case 'integer': def += 'INTEGER'; break;
        case 'boolean': def += 'BOOLEAN DEFAULT false'; break;
        case 'timestamp': def += 'TIMESTAMP DEFAULT NOW()'; break;
        case 'decimal': def += 'DECIMAL(10,2)'; break;
        case 'json': def += 'JSONB'; break;
      }
      if (!col.nullable && !col.primary_key) def += ' NOT NULL';
      if (col.foreign_key) def += ` REFERENCES ${col.foreign_key} ON DELETE CASCADE`;
      return def;
    }).join(',\n');

    const indexes = table.indexes.map(idx =>
      `CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX idx_${table.name}_${idx.columns.join('_')} ON ${table.name}(${idx.columns.join(', ')});`
    ).join('\n');

    return `CREATE TABLE ${table.name} (\n${columns}\n);\n${indexes}`;
  }).join('\n\n');

  return `-- Auto-generated by AppForge Runtime Simulator
-- Generated: ${new Date().toISOString()}

${tables}
`;
}

function verifyCrossReferences(
  schema: SchemaOutput,
  expressRoutes: string,
  dbMigration: string
): { verified: number; issues: string[] } {
  let verified = 0;
  const issues: string[] = [];

  schema.api_schema.endpoints.forEach(ep => {
    if (expressRoutes.includes(ep.path)) {
      verified++;
    } else {
      issues.push(`Endpoint ${ep.path} missing from Express routes`);
    }
  });

  schema.db_schema.tables.forEach(table => {
    if (dbMigration.includes(`CREATE TABLE ${table.name}`)) {
      verified++;
    } else {
      issues.push(`Table ${table.name} missing from DB migration`);
    }
  });

  return { verified, issues };
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}